services:
  # Main proxy service
  proxy:
    build:
      context: .
    ports:
      - "8080:80"
      - "9090:9090"  # metrics endpoint
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BACKEND_HOST=backend
      - BACKEND_PORT=3000
      - LOG_LEVEL=debug
      - ENV=development
    volumes:
      - .:/workspace
    depends_on:
      - redis
      - backend
    develop:
      watch:
        - action: rebuild
          path: ./Dockerfile

  # Redis service (for development/testing only)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_APPENDONLY=yes
    volumes:
      - redis-dev-data:/data

  # Simple backend for testing (development only)
  backend:
    image: httpd:2.4-alpine
    ports:
      - "3000:80"
    volumes:
      - ./tests/fixtures:/usr/local/apache2/htdocs:ro

volumes:
  redis-dev-data:
