services:
  proxy:
    build:
      context: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BACKEND_HOST=backend
      - BACKEND_PORT=3000
      - LOG_LEVEL=debug
      - ENV=development
    volumes:
      - .:/workspace
    develop:
      watch:
        - action: rebuild
          path: ./Dockerfile

  redis:
    environment:
      - REDIS_APPENDONLY=yes
    volumes:
      - redis-dev-data:/data

volumes:
  redis-dev-data:
