services:
  proxy:
    build: .
    ports:
      - "8080:80"
      - "9090:9090"  # metrics endpoint
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BACKEND_HOST=backend
      - BACKEND_PORT=3000
      - LOG_LEVEL=info
    depends_on:
      - redis
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Simple backend for testing
  backend:
    image: httpd:2.4-alpine
    ports:
      - "3000:80"
    volumes:
      - ./tests/fixtures:/usr/local/apache2/htdocs:ro

volumes:
  redis-data:
