services:
  proxy:
    build:
      context: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BACKEND_HOST=backend
      - BACKEND_PORT=3000
      - LOG_LEVEL=debug
      - ENV=development
    volumes:
      - .:/workspace
      - ./nginx/conf:/usr/local/openresty/nginx/conf
      - ./nginx/lua:/usr/local/openresty/nginx/lua
    command: |
      sh -c '
        echo "Starting development server..."
        /usr/local/openresty/bin/openresty -g "daemon off;"
      '
    develop:
      watch:
        - action: sync
          path: ./nginx
          target: /usr/local/openresty/nginx
        - action: rebuild
          path: ./Dockerfile

  redis:
    environment:
      - REDIS_APPENDONLY=yes
    volumes:
      - redis-dev-data:/data

volumes:
  redis-dev-data:
