services:
  # Main proxy service
  proxy:
    build:
      context: .
    ports:
      - "8080:80"
      - "9090:9090"  # metrics endpoint
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BACKEND_HOST=wiremock
      - BACKEND_PORT=8080
      - BACKEND_HEALTHCHECK_PATH=/__admin/health
      - LOG_LEVEL=debug
      - ENV=development
    volumes:
      - .:/workspace
    depends_on:
      - redis
      - wiremock
    develop:
      watch:
        - action: rebuild
          path: ./Dockerfile

  # Redis service (for development/testing only)
  redis:
    image: redis:7-alpine
    environment:
      - REDIS_APPENDONLY=yes
    volumes:
      - redis-dev-data:/data

  # Wiremock backend for flexible API mocking
  wiremock:
    image: wiremock/wiremock:latest
    volumes:
      - ${HOST_WORKSPACE}/wiremock/mappings:/home/wiremock/mappings
      - ${HOST_WORKSPACE}/wiremock/files:/home/wiremock/__files
    command: ["--verbose"]

  cmd:
    image: alpine
    tty: true
    stdin_open: true
    command: ["sh", "-c", "while true; do sleep 3600; done"]

volumes:
  redis-dev-data:
